# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
   #  - 'alerts/*.yml'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  
  - job_name: 'Windows-Exporter'
    metrics_path: /metrics
    static_configs:
         - targets:
            
            - 192.168.10.15:9182


 
 
  - job_name: 'Cadvisor'
    metrics_path: /metrics
    static_configs:
         - targets:

            - 192.168.10.53:8070


  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']



  - job_name: mikrotik
    static_configs:
       - targets:
         - 192.168.110.200:9436
    metrics_path: /metrics

  - job_name: nginx-exporter
    static_configs:
       - targets:
               - 192.168.10.54:9113
               - 192.168.10.54:9114
                 
    metrics_path: /metrics


  - job_name: ping
    scrape_interval: 1m
    scrape_timeout: 40s
    static_configs: 
       - targets:
         - 192.168.110.200:1222
    metrics_path: /metrics

  - job_name: linux
    static_configs:
       - targets:
         - 192.168.110.200:9100
         - 192.168.110.104:9100
    metrics_path: /metrics

  - job_name: 'speedtest-exporter'
    scrape_interval: 180m
    scrape_timeout: 1m
    static_configs:
    - targets: ['192.168.10.54:9112']



  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://rahavard365.com/
        - beta.admin.dohi.mabnadp.com
        - beta.dohi.mabnadp.com
        - beta.v1.dohi.api.mabnadp.com
        - beta.v1.dohi.push.mabnadp.com
        - cf.corp.mabnadp.com
        - jira.corp.mabnadp.com
        - kharazmi.beta.dohi.mabnadp.com
        - kian.beta.dohi.mabnadp.com
        - sina.beta.dohi.mabnadp.com
        - time.corp.mabnadp.com  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.10.53:9115


    
